alias v='vim'
alias vtop='vtop -t dark'
alias cava='cava -p $HOME/Config/cava/config'
alias ls='ls --color -lrpt'

export HPE='/home/mjalvar/Documents/HPE'
export LesPaul='/home/mjalvar/Documents/HPE/LesPaul'

export PATH=$HOME/go/bin:$PATH


PS1='${debian_chroot:+($debian_chroot)}\[\033[00;32m\]\u\[\033[01;32m\]@\h\[\033[00m\]:\[\033[00;32m\]\w\[\033[00m\]\$ '
